[connection]
id=Scanaract_Wifi
uuid=459a19c1-8c35-4130-af36-68d2907a3321
type=wifi
interface-name=wlan0

[wifi]
band=bg
mode=ap
ssid=Scanaract_Wifi

[wifi-security]
group=ccmp;
key-mgmt=wpa-psk
pairwise=ccmp;
proto=rsn;
psk=scanaractpi

[ipv4]
method=shared

[ipv6]
addr-gen-mode=default
method=auto

[proxy]